### ISSUE TITLE
Provide a way to collect useful information (e.g. finding the names of variables) while parsing

### ISSUE THREAD

**Issue by quotquot** [ianchi/ESpression#12]
I used to use `jsep` and I am switching to `ESpression`. I had my own eval function, which is already provided by `ESpression`, but I also had a function to find the names of variables used in an AST. This is useful to reevaluate some expressions when the referenced variables change. Could this feature be useful for other developers and be implemented in the module? Maybe by providing an optional parameter to `parse` that could collect some information, or call a handler for each visited node.

For information, this was my implementation to walk the AST and gather variable names:

```javascript
function _vars(set, ...nodes)
{
    for (let node of nodes)
        switch (node.type) {

            case 'Literal':
            case 'ThisExpression':
                break;

            case 'Compound':
                _vars(set, ...node.body);
                break;

            case 'ArrayExpression':
                _vars(set, ...node.elements);
                break;

            case 'UnaryExpression':
                _vars(set, node.argument);
                break;

            case 'LogicalExpression':
            case 'BinaryExpression':
                _vars(set, node.left, node.right);
                break;

            case 'ConditionalExpression':
                _vars(set, node.test, node.consequent, node.alternate);
                break;

            case 'CallExpression':
                _vars(set, node.callee, ...node.arguments);
                break;

            case 'Identifier':
                set.add(node.name);
                break;

            case 'MemberExpression':
                switch (node.object.type) {
                    case 'Identifier':
                        set.add(node.object.name);
                        break;
                    case 'ThisExpression':
                        set.add(node.property.name);
                        break;
                    case 'MemberExpression':
                        _vars(set, node.object);
                        break;
                    default:
                        throw new Error(`Unhandled member expression ${node.object.type}`);
                }
                break;

            default:
                throw new Error(`unhandled node type ${node.type}`);
        }
}

export function vars(ast)
{
    const set = new Set();
    _vars(set, ast);
    return set;
}
```

**Comment by ianchi** [comment]
Hi @quotquot, catching up a bit late.

This is a valid but very specific use case. I initially considered adding some more general tree-traversing functionality, but there are already good and flexible packages that can handle just that, with any generic node, and so there is no need or benefit in repeating that work here.

One such package is [estree-walker](https://www.npmjs.com/package/estree-walker),  that can traverse any standard or non-standard AST node, as long as it has a `type` property (which is also required for *ESpression*), and so it can handle any custom node configured in the parsing rules.

I suggest that you use it for this kind of tasks.
