### ISSUE TITLE
Async function eval support

### ISSUE THREAD

**Issue by hariprasadiit** [ianchi/ESpression#17]
Thanks for awesome library.

I've found that there's no async function support, similar to [donmccurdy/expression-eval](https://github.com/donmccurdy/expression-eval). any plans to add it?

**Comment by ianchi** [comment]
Hi @hariprasadiit,

Yes they should be fully supported using the extension package for reactive evaluation [espression-rx](https://github.com/ianchi/espression-rx)

With it the *Promise* returned by calling an *async* function is automatically promoted to an *Observable* and the evaluation of the expression returns an *Observable* that emits the resolved **value** of the async function combined with any additional operation used in the expression. Complex combination of async functions is also possible (i.e. an async function used as a parameter for another async function, or combining the results of two functions in one expression)

I said it "should" work, as I haven't done much testing with *Promises*, having worked mainly with observables.

**Comment by hariprasadiit** [comment]
@ianchi It's working thank you.
