### ISSUE TITLE
Question/docs: Is this any safer than eval'ing an unstrusted string directly? 

### ISSUE THREAD

**Issue by fabio-looker** [ianchi/ESpression#2]
My use case is that I would like to allow admin users of a service to define expressions that would evaluate objects to either pass or reject them. The expression would be evaluated server-side.

From the readme, it's not really clear whether passing an expression through this library is intended to make evaluating such an expression safe?

**Comment by ianchi** [comment]
Yes it is much safer as the expr has only access to what you explicitly expose in the context and no statements are ever allowed, so no extra code can be injected

**Comment by fabio-looker** [comment]
Ok thanks! I've already selected a library, but could be worthwhile to put in docs anyway :)
